config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render xml: @kittens }
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render xml: @kitten }
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'A new kitten has been added.'
      redirect_to @kitten
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:success] = 'A kitten has been updated.'
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = 'A kitten has been deleted.'
    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% kitten.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
    <% kitten.errors.full_messages_for(:age).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness %>
    <% kitten.errors.full_messages_for(:cuteness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :softness %><br>
    <%= form.number_field :softness %>
    <% kitten.errors.full_messages_for(:softness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= button_to 'Delete', @kitten, method: :delete %>

<%= render 'form', kitten: @kitten %>

app/views/kittens/index.html.erb
<h1>All kittens</h1>

<%= button_to 'Add new kitten', new_kitten_path, method: :get %>
<ul>
  <% @kittens.each do |k| %>
    <li><%= link_to k.name, k %>  <%= link_to 'Delete', kitten_path(k), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form', kitten: @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<%= button_to 'Edit', edit_kitten_path, method: :get %>
<%= button_to 'Delete', @kitten, method: :delete %>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <p><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>